Adicionando Repositorio ao ConnecTatto
SouJunior/soujunior-lab pull request #71
Opened 2023-02-14 19:55 UTC by GeyzonErik

2023-02-16 20:41 UTC, dansenpir requested changes

2023-02-16 20:41 UTC, dansenpir commented on README.md
>  ## 14. Connect Tattoo
@GeyzonErik necessario corrigir o titulo e link, para se adequar ao novo nome do produto.

2023-02-17 14:37 UTC, GeyzonErik commented
@dansenpir Acabei de trocar o titulo e o nome do Link

2023-02-17 23:32 UTC, dansenpir requested changes
Necessário corrigir o link, @GeyzonErik

2023-02-24 20:46 UTC, GeyzonErik commented
@dansenpir Atualizado o nome do projeto 100% e adicionado target blanck ao link de repositório.

2023-03-01 19:02 UTC, merged